-- SQL Schema Setup for PettyOffice Supabase Database (v1.1)

-- 1. Core Generations Table
CREATE TABLE IF NOT EXISTS public.generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool TEXT NOT NULL,
    country TEXT,
    device TEXT,
    source TEXT DEFAULT 'ai',
    premium_interest INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Visitors Table
CREATE TABLE IF NOT EXISTS public.visitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page TEXT NOT NULL,
    country TEXT,
    device TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Forms Metadata Table (dynamic tile engine)
CREATE TABLE IF NOT EXISTS public.forms_metadata (
    id BIGSERIAL PRIMARY KEY,
    module_type TEXT NOT NULL,
    category_name TEXT NOT NULL,
    emoji_or_icon TEXT NOT NULL DEFAULT '📋',
    description_text TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Rate Limiting Table (serverless-safe, per-IP sliding window)
CREATE TABLE IF NOT EXISTS public.rate_limits (
    ip_hash TEXT PRIMARY KEY,
    request_count INTEGER DEFAULT 1,
    window_start TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Shared Documents Table (viral shareable cases)
CREATE TABLE IF NOT EXISTS public.shared_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    module_type TEXT NOT NULL,
    primary_selection TEXT NOT NULL,
    secondary_selection TEXT,
    document_content TEXT NOT NULL,
    view_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. LLM Response Cache (deduplicate identical inputs, 24h freshness window)
CREATE TABLE IF NOT EXISTS public.llm_cache (
    input_hash TEXT PRIMARY KEY,
    module_type TEXT NOT NULL,
    primary_selection TEXT NOT NULL,
    secondary_selection TEXT,
    response TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Enable Row Level Security (RLS)
ALTER TABLE public.generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forms_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shared_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_cache ENABLE ROW LEVEL SECURITY;

-- 8. RLS Policies
-- generations: anonymous inserts only; reads via service_role only
CREATE POLICY IF NOT EXISTS "Allow anonymous inserts only"
ON public.generations
FOR INSERT
TO anon
WITH CHECK (true);

-- visitors: anonymous inserts only
CREATE POLICY IF NOT EXISTS "Allow anonymous inserts only"
ON public.visitors
FOR INSERT
TO anon
WITH CHECK (true);

-- forms_metadata: public read active rows only
CREATE POLICY IF NOT EXISTS "Public can read active forms"
ON public.forms_metadata
FOR SELECT
USING (is_active = true);

-- rate_limits, shared_documents, llm_cache: no public access; service_role only
CREATE POLICY IF NOT EXISTS "Service role only"
ON public.rate_limits
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Service role only"
ON public.shared_documents
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Service role only"
ON public.llm_cache
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- 9. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_generations_tool ON public.generations(tool);
CREATE INDEX IF NOT EXISTS idx_generations_created_at ON public.generations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_generations_country ON public.generations(country);
CREATE INDEX IF NOT EXISTS idx_visitors_page ON public.visitors(page);
CREATE INDEX IF NOT EXISTS idx_visitors_created_at ON public.visitors(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitors_device ON public.visitors(device);
CREATE INDEX IF NOT EXISTS idx_forms_metadata_active ON public.forms_metadata(is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_rate_limits_window ON public.rate_limits(window_start);
CREATE INDEX IF NOT EXISTS idx_shared_documents_created ON public.shared_documents(created_at);
CREATE INDEX IF NOT EXISTS idx_llm_cache_created ON public.llm_cache(created_at);
